/**
 * interfaces.ts — ALL TypeScript interfaces for the entire app.
 *
 * This is the single source of truth for data shapes. Both the frontend
 * services and Cloud Functions follow these structures (Cloud Functions
 * in JS, so they just produce matching JSON).
 *
 * NAMING CONVENTION:
 *   - Firestore doc shapes: UserProfile, ChatMessage, GameDay, etc.
 *   - LLM response shapes: ReframeAnalysis, LiveGauges, FutureVision, etc.
 *   - Type unions: AgentId, TileType, ConsequenceType, GameDayState
 *
 * ROLES:
 *   - 'member'  → standard user (all features except Intelligence)
 *   - 'founder' → access to Intelligence page (founderGuard)
 *   - 'admin'   → same as founder (no admin UI yet)
 */
import { Timestamp } from 'firebase/firestore';

// ── User Profile (Firestore: users/{uid}) ────────────────────
export interface UserProfile {
  uid: string;
  email: string;
  role: 'member' | 'founder' | 'admin';
  createdAt: Timestamp;
  onboarding: OnboardingData;
  profile?: GeneratedProfile;
  genomeData?: GenomeEntry[];
}

/** Collected during 5-step onboarding flow. Fed to LLM for profile generation. */
export interface OnboardingData {
  // Section A — Identity
  name: string;
  birthDate: string;
  birthTime: string;
  birthLocation: string;

  // Section B — Personality & Values
  strengths: string[];
  communicationStyle: 'direct' | 'warm' | 'analytical' | 'reserved';
  spiritualOrientation: string;
  chronotype: 'morning' | 'night';
  riskTolerance: number; // 1-10

  // Section C — Life Priorities
  healthPriorities: string[];
  financialPriorities: string[];
  relationshipGoals: string[];
  careerDirection: string;

  // Section D — Preferences
  tonePref: 'direct' | 'warm' | 'analytical' | 'minimal';
  newsTopics: string[];
  exclusions: string[];
  noveltyMode: 'stabilize' | 'expand' | 'accelerate';
}

/** Generated by onProfileGenerate Cloud Function. Drives theme, dashboard, and all personalization. */
export interface GeneratedProfile {
  archetypeName: string;
  coreStrength: string;
  shadowToTransmute: string;
  primaryExpressionMode: string;
  seasonalFocus: string;
  energyTheme: 'clarity' | 'healing' | 'heart' | 'growth' | 'activation';
  colorKeyword: 'gold' | 'teal' | 'rose' | 'emerald' | 'amber';
  wheelOfLife: WheelOfLife;
  dailyGuidance: {
    alignedActions: string[];
    thingToRelease: string;
  };
  personalitySummary: string;
}

/** Initial dimension scores (5-100) set during profile generation. Used to seed DimensionScores. */
export interface WheelOfLife {
  spirit: number;
  body: number;
  relationships: number;
  wealth: number;
  creativeExpression: number;
  service: number;
  learning: number;
  environment: number;
}

// ── Genome ───────────────────────────────────────────────────
export interface GenomeEntry {
  rsId: string;
  chromosome: string;
  position: number;
  genotype: string;
}

// ── Chat (Firestore: users/{uid}/chat_history/{agentId}/threads/{threadId}/messages/{id}) ──
/** The 5 advisor personas. Each has a unique system prompt in functions/index.js. */
export type AgentId =
  | 'financial'
  | 'food-medicine'
  | 'media'
  | 'relationship'
  | 'moonshot';

export interface ChatMessage {
  id?: string;
  role: 'user' | 'assistant';
  content: string;
  agentId: AgentId;
  timestamp: Timestamp;
}

export interface ChatThread {
  id?: string;
  title: string;
  createdAt: Timestamp;
  lastMessageAt: Timestamp;
}

// ── ReframeOS / Communication Intelligence (returned by onReframeSubmit) ──
/** Analysis result from journal entry submission. Includes language pattern scores and reframes. */
export interface ReframeAnalysis {
  patternsDetected: string[];
  scores: {
    agency: number;
    blame: number;
    certainty: number;
    futureOrientation: number;
    emotionalPolarity: number;
  };
  emotion: {
    primary: string;
    secondary?: string;
    intensity: number;
  };
  reframes: Reframe[];
  vocabularyUpgrades: VocabUpgrade[];
  genekeysAlignment?: GeneKeysAlignment[];
}

export interface Reframe {
  title: string;
  reframeText: string;
  whyItWorks: string;
  nextAction: string;
}

export interface VocabUpgrade {
  weakPhrase: string;
  strongReplacement: string;
  rationale: string;
}

export interface GeneKeysAlignment {
  geneKey: string;
  frequencyDetected: 'shadow' | 'gift' | 'siddhi' | 'mixed';
  languageEvidence: string[];
  suggestedGiftReframe: string;
}

export interface LexiconItem {
  id?: string;
  weakPhrase: string;
  strongReplacement: string;
  rationale: string;
  usageCount: number;
  createdAt: Timestamp;
}

// ── Live Mode Gauges (returned by onLiveAnalyze, polled every 8s) ──
export interface LiveGauges {
  volumeLevel: number;
  pace: number;
  talkTimeRatio: number;
  interruptionCount: number;
  emotionalIntensity: number;
  empathySignals: number;
  angerEdge: number;
  clarity: number;
  overallAlignment: number;
  microPrompt: string | null;
}

// ── Inspiration Feed ─────────────────────────────────────────
export interface FutureVision {
  category: 'food' | 'money' | 'medicine' | 'media' | 'relationships';
  title: string;
  visionText: string;
}

export interface EditionItem {
  id: string;
  title: string;
  url: string;
  source: string;
  summary: string;
  category: string;
}

export interface Edition {
  editionId: string;
  userId: string;
  date: string;
  items: EditionItem[];
  createdAt: Timestamp;
}

// ── Intelligence Agent ───────────────────────────────────────
export interface TranscriptExtraction {
  id?: string;
  transcriptFileUrl: string;
  fileName: string;
  executiveSummary: string;
  nuggets: string[];
  decisionsMade: Decision[];
  openLoops: OpenLoop[];
  actionItems: ActionItem[];
  entitiesMentioned: EntityMention[];
  risks: string[];
  threadUpdates: string[];
  createdAt: Timestamp;
}

export interface Decision {
  decision: string;
  context: string;
}

export interface OpenLoop {
  question: string;
  whoOwesAnswer: string;
  priority: 'high' | 'medium' | 'low';
}

export interface ActionItem {
  action: string;
  suggestedOwner: string;
  urgency: 'immediate' | 'this-week' | 'soon' | 'backlog';
}

export interface EntityMention {
  name: string;
  type: 'person' | 'org' | 'project' | 'asset';
  context: string;
}

export interface Thread {
  id?: string;
  title: string;
  summaryCurrent: string;
  status: 'active' | 'waiting' | 'stalled' | 'resolved';
  keyEvents: ThreadEvent[];
  openLoops: string[];
  nextBestActions: string[];
  relatedEntities: string[];
  lastMentionedAt: Timestamp;
  createdAt: Timestamp;
}

export interface ThreadEvent {
  transcriptId: string;
  summary: string;
  date: Timestamp;
}

// ── Daily Briefing ───────────────────────────────────────────
export interface DailyBriefing {
  date: string;
  financialInsight: string;
  healthSuggestion: string;
  headlines: BriefingHeadline[];
  relationshipReflection: string;
  growthReminder: string;
  createdAt: Timestamp;
}

export interface BriefingHeadline {
  title: string;
  url?: string;
  source?: string;
}

// ── File Upload ──────────────────────────────────────────────
export interface UploadedFile {
  id?: string;
  fileName: string;
  fileUrl: string;
  fileType: string;
  category: string;
  tags: string[];
  summary: string;
  createdAt: Timestamp;
  source?: 'local' | 'drive';
}

// ── Feedback ─────────────────────────────────────────────────
export interface Feedback {
  userId: string;
  itemId: string;
  action: 'up' | 'down';
  timestamp: Timestamp;
}

// ── Memory Layer (Firestore: users/{uid}/memory/core) ────────
/** Persistent memory that the LLM accumulates about the user across all interactions.
 *  Caps: 10 insights, 8 patterns, 5 avoidances, 5 strengths. See mergeMemory() in functions/index.js. */
export interface UserMemory {
  coreInsights: string[];
  activePatterns: MemoryPattern[];
  avoidances: string[];
  strengths: string[];
  agentInsights: Record<string, string>;
  currentEdge: string;
  lastUpdated: Timestamp;
}

export interface MemoryPattern {
  pattern: string;
  frequency: number;
  lastSeen: string;
}

export interface MemoryUpdate {
  newInsights: string[];
  updatedPatterns: string[];
  removeInsights: string[];
  avoidanceSignal: string | null;
}

// ── Personalized Runtime / Agent Orchestration ──────────────
export type SpecializedAgentType = 'knowledge' | 'research' | 'memory' | 'recommendation';

export interface RetrievedEvidence {
  documentId: string;
  chunkId: string;
  text: string;
  score: number;
  sourceType: string;
  sourceName: string;
  metadata: Record<string, unknown>;
}

export interface AvailableAgent {
  id: SpecializedAgentType;
  name: string;
  description: string;
  capabilities: string[];
}

export interface PersonalizedRespondResult {
  response: string;
  selectedAgent: SpecializedAgentType;
  evidence: RetrievedEvidence[];
  retrievalStatus: 'ok' | 'empty' | 'degraded';
  memoryUpdateQueued: boolean;
}

export interface RunAgentTaskResult {
  result: string;
  agentType: SpecializedAgentType;
  evidence: RetrievedEvidence[];
  retrievalStatus: 'ok' | 'empty' | 'degraded';
}

// ── Password Vault ──────────────────────────────────────────
export interface VaultKdfParams {
  algorithm: 'argon2id';
  iterations: number;
  memorySize: number;
  parallelism: number;
  hashLength: number;
  salt: string;
}

export interface EncryptedVaultPayload {
  iv: string;
  ciphertext: string;
}

export interface VaultConfig {
  cryptoVersion: number;
  kdf: VaultKdfParams;
  wrappedVaultKeyByPassword: EncryptedVaultPayload;
  wrappedVaultKeyByRecovery: EncryptedVaultPayload;
  passwordVerifier: EncryptedVaultPayload;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface VaultLoginSecretData {
  username: string;
  password: string;
  url: string;
  notes: string;
}

export interface VaultLoginItem {
  id?: string;
  type: 'login';
  title: string;
  provider: string;
  favorite: boolean;
  tags: string[];
  encryptedPayload: EncryptedVaultPayload;
  cryptoVersion: number;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface VaultLoginItemInput {
  title: string;
  provider: string;
  favorite: boolean;
  tags: string[];
  username: string;
  password: string;
  url: string;
  notes: string;
}

export interface VaultSessionState {
  isConfigured: boolean;
  isUnlocked: boolean;
  unlockedAt: number | null;
}

// ── Dynamic Dimension Scores (Firestore: users/{uid}/scores/current) ──
/** Live scores that decay over time and respond to game choices + actions.
 *  See ScoringService for the math. lastActivity tracks per-dimension dates for decay. */
export interface DimensionScores {
  spirit: number;
  body: number;
  relationships: number;
  wealth: number;
  creativeExpression: number;
  service: number;
  learning: number;
  environment: number;
  lastActivity: Record<string, string>;
  lastDate: string;
}

// ── Game of Life (Firestore: users/{uid}/game_days/{date}) ──
/** 6 base tile types. LLM selects one per day based on patterns, avoidance, and lowest scores. */
export type TileType = 'mirror' | 'risk' | 'shadow' | 'vitality' | 'relationship' | 'unknown';
export type AdvancedTileType = 'co-creation' | 'wealth-energy' | 'service-mission' | 'relationship-lab' | 'leadership-trial' | 'silence-retreat' | 'regenerative-project';
export type GameDayState = 'pending_choice' | 'in_progress' | 'completed';
export type ConsequenceType = 'avoid' | 'explore' | 'act' | 'transmute';

export interface TileChoice {
  label: string;
  description: string;
  consequenceType: ConsequenceType;
  linkedDimension: keyof WheelOfLife;
}

export interface DailyAction {
  id: string;
  title: string;
  description: string;
  tileType: TileType;
  linkedDimension: keyof WheelOfLife;
  completed: boolean;
  completedAt?: Timestamp;
}

export interface GameDay {
  date: string;
  tileType: TileType;
  tilePrompt: string;
  choices: TileChoice[];
  chosenPath: number | null;
  choiceConsequences: Record<string, number> | null;
  state: GameDayState;
  actions: DailyAction[];
  yesterdayAnalysis: string;
  shadowProgression?: { shadow: string; gift: string; siddhi: string };
  createdAt: Timestamp;
}

export interface DaySnapshot {
  date: string;
  scores: DimensionScores;
  tileType: TileType;
  chosenPath: number | null;
  consequenceType: ConsequenceType | null;
  actionsServed: number;
  actionsCompleted: number;
  actionsSkipped: number;
}

export interface CoherenceMetrics {
  streak: number;
  totalChoices: number;
  courageChoices: number;
  transmutations: number;
  boardLevel: number;
}

export interface EntryCalibration {
  wantMore: string;
  drains: string;
  afraidToRisk: string;
  aliveButUncertain: string;
  savedAt: Timestamp;
}

export interface TodoItem {
  id?: string;
  title: string;
  linkedDimension?: keyof WheelOfLife;
  source: 'tile' | 'manual';
  completed: boolean;
  createdAt: Timestamp;
  completedAt?: Timestamp;
}
